[package]
name = "blog-client"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { version = "1.49", features = ["rt", "macros"], default-features = false }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio.workspace = true

[dependencies]
thiserror.workspace = true
reqwest = { version = "0.13", features = ["json"] }
tonic.workspace = true
serde_json.workspace = true
serde.workspace = true
chrono.workspace = true
prost-types.workspace = true
prost.workspace = true
tonic-prost.workspace = true


[build-dependencies]
tonic-prost-build = "0.14"