[package]
name = "blog-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[build]
target = "wasm32-unknown-unknown"


[dependencies]
blog-client = { path = "../blog-client" }
wasm-bindgen="0.2"
wasm-bindgen-futures = "0.4"
serde-wasm-bindgen = "0.6"
js-sys="0.3"
web-sys = { version = "0.3", features = [
    "console",
    "Window",
    "Document",
    "Element",
    "HtmlElement",
    "HtmlInputElement",
    "HtmlTextAreaElement",
    "HtmlButtonElement",
    "Event",
    "EventTarget",
    "KeyboardEvent",
    "InputEvent",
    "SubmitEvent",
    "Storage",
] }
