[package]
name = "blog-server"
version = "0.1.0"
edition = "2024"
build = "build.rs"


[dependencies]
actix-web="4.12"
actix-cors="0.7"
jsonwebtoken = { version = "10.2", features = ["rust_crypto"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
sqlx= { version = "0.8" , features = [
    "runtime-tokio-rustls",
    "postgres",
    "uuid",
    "chrono",
    "migrate",
] }
tonic.workspace = true
serde.workspace = true
chrono.workspace = true
anyhow = "1.0"
dotenvy.workspace = true
thiserror.workspace = true
argon2 = "0.5"
password-hash = "0.5"
serde_json.workspace = true
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json", "chrono", "time"] }
futures-util = "0.3"
actix-service = "2.0"
prost-types.workspace = true
prost.workspace = true
tonic-prost.workspace = true
uuid = { version = "1.18.1", features = ["v4"] }

[build-dependencies]
tonic-prost-build = "0.14"